### ISSUE TITLE
Cannot add ethernet ports in the on-demand options

### ISSUE THREAD

**Issue by paderijk** [passepartoutvpn/passepartout#1010]
# Summary

When connecting an iPad with ethernet, you cannot add the ethernet in the on-demand options. On the iPhone you can toggle mobile networks in the on-demand settings.

### Steps to reproduce

Connect an ethernet port to your iPad and go to the settings for on-demand.

### What is the current bug behavior?

Ethernet port does not show up as option to be toggled, like you can do with mobile networks in the on-demand settings.

### What is the expected correct behavior?

An option to toggle ethernet ports in the on-demand settings.

### Relevant logs and/or screenshots

n.a.

### Possible fixes suggested remediation

Add an option to toggle ethernet ports in the on-demand settings or even certain IP-ranges to specify some more details for networks to be toggled.

**Comment by keeshux** [comment]
https://github.com/passepartoutvpn/passepartout/blob/750b12c4eef061580fb719a0bf8d689bbd5b10d0/Library/Sources/CommonUtils/Extensions/Utils%2BNetwork.swift#L59

**Comment by keeshux** [comment]
@paderijk #1012 should fix this, but I will need you to try the next TestFlight build -I'd tell you when- to confirm that this works on your device.

**Comment by keeshux** [comment]
@paderijk build 3686 on TestFlight has this change, please let me know.

**Comment by paderijk** [comment]
> @paderijk build 3686 on TestFlight has this change, please let me know.

@keeshux - Thanks for the quick response! Tested it via TestFlight and works as expected!
