### ISSUE TITLE
Siri does not work with encrypted DNS when VPN is default gateway (Apple bug)

### ISSUE THREAD

**Issue by BetaMatrixCompositor** [passepartoutvpn/passepartout#182]
Setting custom DNS (either DoH or DoT) through Passepartout causes Siri to display a message that Siri is unavailable (stating the iPhone is not connected to the internet.) 

Using cleartext DNS or the VPN’s DNS does not cause this issue. I am not sure more Apple services are affected, and whether some connectivity check is failing. Verified this behaviour on both an iPhone and an iPad with iOS 14.4.2.

---

*EDIT*

Known bug? https://developer.apple.com/forums/thread/677812

Basic test:

- Configuration
  - DNS over HTTPS
  - Servers
    - 1.1.1.1
    - 1.0.0.1
  - URL
    - https://1.1.1.1/dns-query

Confirmed to be correctly configured on https://1.1.1.1/help/

Test:

- Connect to the VPN
- Try "Hey Siri"
- "Siri is not available. iPhone is not connected to the Internet"

Test DOES work when using CloudFlare 1.1.1.1 app though (in fact, it's not the default gateway).

**Comment by JGitHubB** [comment]
Same issue there. Are you planning a fix?

**Comment by keeshux** [comment]
A quick test revealed that the issue DOES NOT happen when the VPN is not the default gateway.

**Comment by keeshux** [comment]
https://developer.apple.com/forums/thread/677812

**Comment by keeshux** [comment]
You can tell from the forum thread that this is an Apple issue. Siri has never worked with encrypted DNS since iOS 14 released the feature.
