### ISSUE TITLE
Run Shortcuts without opening app

### ISSUE THREAD

**Issue by thsmdt** [passepartoutvpn/passepartout#214]
Hi again 😄

Currently, when using a shortcut to connect to or disconnect from a VPN, the Passepartout App will open; however, this is sometimes undesired. It would be great if the shortcut ran in the background entirely. Further, this is necessary for shortcuts activated as automation when opening an app.

For instance, a user may use a business app that requires access to a company's internal network. Yet, being connected to the VPN is undesired outside of this app. A user can use Shortcuts' automation feature, so they don't need to remember to enable/disable the VPN on their own, which is a significant convenience.

With the current behavior of opening Passepartout in the foreground on invocation of the shortcut, the business app cannot even be reached anymore, as Passepartout displaces it, and switching back into the business app will cause the shortcut to be triggered yet again.

---

*EDIT*

Maybe https://developer.apple.com/documentation/appintents/

Discoveries:

- Unknown error when running VPN commands through extension. As in command succeeds, but Siri communicates failure. VPN unaffected.
- Claims [ProtonVPN does it](https://github.com/passepartoutvpn/passepartout-apple/issues/214#issuecomment-1124574967)
- Siri reported to run in background in iOS 16.4
- https://www.reddit.com/r/passepartout/comments/12dwav1/discussion_ios_164_set_vpn_action_in_shortcuts/
- https://www.reddit.com/r/passepartout/comments/10nw6f0/discussion_shortcuts_vpn_background_potential/

**Comment by mazulatas** [comment]
This problem is also relevant for me, I would like the connection to be established in the background.

**Comment by keeshux** [comment]
https://passepartoutvpn.app/faq/#why-dont-siri-shortcuts-execute-in-the-background

**Comment by rudeqit** [comment]
Got same problem. But how for example protonvpn can connect to vpn by shortcut? They use native VPN protocols (IKEv2, IPsec etc.)?

**Comment by keeshux** [comment]
Resolved in version 3.0.0
