### ISSUE TITLE
VPN stops working on switching from wifi to cellophane or cellular to wifi 

### ISSUE THREAD

**Issue by binusebastian** [passepartoutvpn/passepartout#216]
VPN stops working on switching from wifi to cellophane or cellular to wifi. Status of the vpn is active and vpn debug says ping received, do nothing. How can I fix this? When this happens I cannot ping anything on the internet (like 1.1.1.1 or 8.8.8.8). I will have to turn off and turn on data and wifi to fix this. Turning off vpn and turning it back on will also fix it.

**Comment by keeshux** [comment]
Duplicate of #204
