### ISSUE TITLE
Suggest that closing the app does not shut down the connection

### ISSUE THREAD

**Issue by verum-haeresis** [passepartoutvpn/passepartout#223]
Hi. When I'm close Passepartout (CMD+Q / or click Quit Passepartout at Menu Bar) the VPN connection is active.

For example when I want to quit Passepartout and enable IKEv2 VPN configured at MacOS Network Preferences I should disable VPN connection at Passepartout and after that enable IKEv2. I can't just quit Passepartout to stop VPN (otherwise Passepartout will try to reconnect).

**Comment by keeshux** [comment]
It might be misleading but this is intended behavior. The app is just a tunnel manager, which in turn is a separate process. Granted, UI might be improved with that in mind.

**Comment by keeshux** [comment]
I restored in 2.0 the confirmation alert from version 1.x, behavior should be clearer now:

<img width="275" alt="Screen Shot 2022-09-24 at 09 27 07" src="https://user-images.githubusercontent.com/805724/192085814-5c797eda-621e-45a1-9d55-57efbc9c4615.png">

Thanks for the report!

**Comment by keeshux** [comment]
CMD+Q on Catalyst actually ignores anything in its way.
