### ISSUE TITLE
Feature Request - Siri, Add shortcut, VPN, Toggle VPN

### ISSUE THREAD

**Issue by m-hume** [passepartoutvpn/passepartout#343]
# Summary
Would it be possible to add an extra item to the Siri - Add shortcut - VPN menu to toggle the state of the VPN?

Thanks

**Comment by keeshux** [comment]
You have it already, or I don’t understand the question.

**Comment by m-hume** [comment]
Currently you can add siri shortcut to Enable the VPN and a second shortcut to Disable the VPN
A single toggle shortcut would change the VPN to the opposite state

### [toggle](https://www.google.com/search?q=toggle+meaning)
switch from one effect, feature, or state to another by using a toggle.
"the play/pause button toggles between those functions"

**Comment by keeshux** [comment]
Ah, I see now! Fair.

**Comment by keeshux** [comment]
Duplicate of #610
