### ISSUE TITLE
[Feature Request] Support for Shortcuts in macOS 

### ISSUE THREAD

**Issue by roboslone** [passepartoutvpn/passepartout#370]
# Summary
Currently on macOS to connect to a VPN I have to:
* click on menubar icon
* move mouse to a VPN configuration (I have several)
* move mouse to a submenu
* click "Connect"

If Passepartout was supported in Shortcuts app, I could create a shortcut to toggle each VPN configuration. Then it would be available in RayCast and I wouldn't need a mouse at all.

**Comment by francescomalandrino** [comment]
subscribing!

this would also enable controlling VPNs via terminal/scripts, which is very useful in many contexts

**Comment by keeshux** [comment]
Supported in 3.0.0
