### ISSUE TITLE
The selected vpn does not update in the list in the menu bar of the app

### ISSUE THREAD

**Issue by d0sse** [passepartoutvpn/passepartout#482]
When you change a vpn from the menu bar, the old one stays selected when you reopen the menu. 
If you open the application window active and deactivate the menu it returns correct

<img width="1334" alt="Screenshot 2024-01-19 at 12 21 03" src="https://github.com/passepartoutvpn/passepartout-apple/assets/16508608/7b151d20-46dc-47c6-8524-deb73209ed88">

**Comment by holdit** [comment]
I have the same problem. Started a few weeks ago, I think.

Still happening with the current version (2.3.5) on Sanoma 14.2.1.

**Comment by Neifab** [comment]
Hello all, same here.

**Comment by VSKut** [comment]
Similar issue #494

**Comment by holdit** [comment]
> Similar issue #494

That's the same issue I have.

**Comment by sample** [comment]
Have same problem on latest Sonoma and app verson

**Comment by au-ganymede** [comment]
Unfortunately, I am experiencing the same problem.
macOS Sonoma 14.5
