### ISSUE TITLE
Packets sent through an OpenVPN TAP tunnel are missing the Ethernet header

### ISSUE THREAD

**Issue by glovaschi** [passepartoutvpn/passepartout#493]
# Summary

Packets sent by the Passepartout app for iOS through an OpenVPN TAP tunnel are missing the Ethernet header. A tcpdump on the server reveals that the Ethernet frame that comes from the Passsepartout client is actually an IP packet (the Ethernet payload) and the Ethernet header is missing.

### Steps to reproduce

Set up an OpenVPN TAP tunnel and observe the frames received by the server from the client.

### What is the current bug behavior?

Ethernet frames are missing the header.

### What is the expected correct behavior?

Ethernet frames should be sent with a header.

### Relevant logs and/or screenshots

I attached a sample client config (tap-client.ovpn) and an Ethernet capture from the TAP interface on the OpenVPN server (tap.pcap) in the archive [tap.zip](https://github.com/passepartoutvpn/passepartout-apple/files/14211767/tap.zip).

**Comment by keeshux** [comment]
Unfortunately, I don't know how to either reproduce or fix this. I have to close it as wontfix.
