### ISSUE TITLE
Incorrect status display when switching to a different vpn

### ISSUE THREAD

**Issue by juev** [passepartoutvpn/passepartout#494]
# Summary

### Steps to reproduce

Multiple VPN connection profiles are configured on my phone. If passepartout is active, we switch to using a different VPN in the system settings.

![IMG_9207](https://github.com/passepartoutvpn/passepartout-apple/assets/114635/1274911e-238e-4d09-9fe0-5ec412a571bf)

### What is the current bug behavior?

In passepartout, we can see the status connected, but not active. Which is incorrect.

![IMG_9208](https://github.com/passepartoutvpn/passepartout-apple/assets/114635/63071688-89b9-4fa7-a523-2e3a0cc3ff9e)

### What is the expected correct behavior?

When switching vpn to another one in the system settings, in passepartout we see the disabled status.

**Comment by VSKut** [comment]
The situation is similar on macOS

https://github.com/passepartoutvpn/passepartout-apple/assets/1468809/088c7764-5d45-4edb-8bd6-601ab004cd61

I open the tab (program's ui) with OpenVPN, but connect to WireGuard - in macos menubar it will be displayed that I am connected to OpenVPN

**Comment by keeshux** [comment]
This will be fixed in v3.
