### ISSUE TITLE
NordVPN might be requiring a specific OpenVPN password

### ISSUE THREAD

**Issue by keeshux** [passepartoutvpn/passepartout#495]
It used to be the website's password, but this may be discontinued soon.

**Comment by kamushadenes** [comment]
Obtainable here: https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/

**Comment by kamushadenes** [comment]
Please consider something like https://github.com/mustafachyi/NordVPN-WireGuard-Config-Generator/blob/main/src/nordvpn/main.go for support NordLynx
