### ISSUE TITLE
Feature: bypass ip?

### ISSUE THREAD

**Issue by dragon2611** [passepartoutvpn/passepartout#554]
Would it be possible to have a setting for IPs that bypass the vpn?

That said I’m not sure if there is an iOS bug at play as I have a wireguard conf file from the official client with RFC1918 addresses excluded and yet with VPN active I can no longer access a device on a different vlan.

This happens with both this app and the official wireguard client

**Comment by dragon2611** [comment]
Worked around it for now by adding a 2nd endpoint to the profile (since the local router can do WireGuard)

**Comment by keeshux** [comment]
In the new beta, you can add an "IP module" where to exclude specific routes from the VPN. You may want to give it a shot.
