### ISSUE TITLE
Profile locking via iCloud?

### ISSUE THREAD

**Issue by dragon2611** [passepartoutvpn/passepartout#555]
Is it possible to implement some kind of profile locking in iCloud to either bind a profile to a specific device or sync the usage state of the profile.

this is because some vpn connections (especially wireguard) will cause conflicts if 2 devices try to use the same profile at the same time.

**Comment by keeshux** [comment]
Similar to the approach with the Apple TV, I mean to make iCloud sharing a per-profile toggle. I guess this would resolve your issue, right?

**Comment by dragon2611** [comment]
That would probably work, thanks
