### ISSUE TITLE
Problem with iOS and Openvpn

### ISSUE THREAD

**Issue by gianluca-plc** [passepartoutvpn/passepartout#699]
I have an OpenVPN server that has always worked, even with iOS, but I believe it stopped working since I updated to iOS 17. I've tested it, and the client works on Android and Windows, but it doesn't work on iOS anymore.

This is server conf:

port 1195
proto tcp
auth sha1
dev tun

ca ca.crt
cert server.crt
key server.key  # This file should be kept secret
dh dh1024.pem

server 10.9.0.0 255.255.255.0
client-config-dir /etc/openvpn/ccd
route 192.168.83.0 255.255.255.0
route 192.168.87.0 255.255.255.0
route 192.168.59.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "route 192.168.83.0 255.255.255.0"
push "route 192.168.87.0 255.255.255.0"
push "route 192.168.59.0 255.255.255.0"
client-to-client
keepalive 10 120
cipher BF-CBC        # Blowfish (default)
max-clients 16
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status2.log
log-append  openvpn2.log

verb 4

this client

client
dev tun
remote .... 1195
proto tcp
auth sha1
cipher BF-CBC        # Blowfish (default)

max-routes 300
tun-mtu 1400
mssfix 1400
tls-client

<ca>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</ca>

<cert>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----
</key>

verb 4

log from app
09:42:48 - 	IPv6: not configured
09:42:48 - 	Routes (IPv4): [{192.168.83.0/255.255.255.0 *}, {192.168.87.0/255.255.255.0 *}, {192.168.59.0/255.255.255.0 *}, {192.168.88.0/255.255.255.0 *}, {10.9.0.0/255.255.255.0 *}]
09:42:48 - 	Keep-alive interval: 10s
09:42:48 - 	Keep-alive timeout: 2m
09:42:48 - Routing.IPv4: Adding route 192.168.83.0/255.255.255.0 -> 10.9.0.49
09:42:48 - Routing.IPv4: Adding route 192.168.87.0/255.255.255.0 -> 10.9.0.49
09:42:48 - Routing.IPv4: Adding route 192.168.59.0/255.255.255.0 -> 10.9.0.49
09:42:48 - Routing.IPv4: Adding route 192.168.88.0/255.255.255.0 -> 10.9.0.49
09:42:48 - Routing.IPv4: Adding route 10.9.0.0/255.255.255.0 -> 10.9.0.49
09:42:48 - DNS: No settings provided, using current network settings
09:42:48 - Ack successfully written to LINK for packetId 32
09:42:48 - Ack successfully written to LINK for packetId 33
09:42:48 - Ack successfully written to LINK for packetId 34
09:42:48 - Ack successfully written to LINK for packetId 35
09:42:48 - Reasserting flag cleared
09:42:48 - Tunnel interface is now UP
09:42:58 - Trigger shutdown (error: native(code: __C.OpenVPNErrorCode))
09:42:58 - Session did stop with error: native(code: __C.OpenVPNErrorCode)
09:42:58 - Send ping
09:42:58 - Failed LINK read: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected"
09:42:58 - Socket state is cancelled (endpoint: <masked> -> in progress)

**Comment by keeshux** [comment]
Not enough information. Re-test when 3.0.0 is out.
