### ISSUE TITLE
Make more useful Wireguard parse error messages

### ISSUE THREAD

**Issue by l4kr** [passepartoutvpn/passepartout#894]
Hi! 
It would be good to have more useful errors when importing Wireguard configs.

This is what Passepartout says:
<img width="470" alt="SCR-20241119-ohmu" src="https://github.com/user-attachments/assets/e6610fa2-ada1-4e39-98a5-40e6c18da912">

This is what a normal Wireguard client says:
<img width="247" alt="SCR-20241119-ohjy" src="https://github.com/user-attachments/assets/86024850-3f9e-4114-bb4b-fa741421ac70">

The Wireguard client tells me exactly what's wrong while Passepartout is vague about the issue...

**Comment by keeshux** [comment]
LOL, you are absolutely right, I was already aware of the issue. Thanks. :-)
